from django.conf.urls import *

urlpatterns = patterns(
    '',
    url(r'^info$', 'workspace.manageAccount.views.edit_info', name='admin_manager.edit_info'),
    url(r'^info-update$', 'workspace.manageAccount.views.edit_info_update', name='admin_manager.edit_info_update'),
    url(r'^users$', 'workspace.manageAccount.views.index_users', name='admin_manager.index_users'),
    url(r'^branding$', 'workspace.manageAccount.views.edit_branding', name='admin_manager.edit_branding'),
    url(r'^branding-update$', 'workspace.manageAccount.views.edit_branding_update', name='admin_manager.edit_branding_update'),
    url(r'^social$', 'workspace.manageAccount.views.edit_social', name='admin_manager.edit_social'),
    url(r'^social_update$', 'workspace.manageAccount.views.edit_social_update', name='admin_manager.edit_social_update'),
    url(r'^domain$', 'workspace.manageAccount.views.edit_domain', name='admin_manager.edit_domain'),
    url(r'^domain-update$', 'workspace.manageAccount.views.edit_domain_update', name='admin_manager.edit_domain_update'),
    url(r'^categories$', 'workspace.manageAccount.views.index_categories', name='admin_manager.index_categories'),
    url(r'^create_category$', 'workspace.manageAccount.views.create_categories', name='admin_manager.create_categories'),
    url(r'^edit_category$', 'workspace.manageAccount.views.edit_categories', name='admin_manager.edit_categories'),
    url(r'^delete_category$', 'workspace.manageAccount.views.delete_categories', name='admin_manager.delete_categories'),
    url(r'^create_user$', 'workspace.manageAccount.views.create_user', name='admin_manager.create_user'),
    url(r'^edit_user$', 'workspace.manageAccount.views.edit_user', name='admin_manager.edit_user'),
    url(r'^check_email$', 'workspace.manageAccount.views.check_email', name='admin_manager.check_email'),
    url(r'^check_username', 'workspace.manageAccount.views.check_username', name='admin_manager.check_username'),
    url(r'^check_domain', 'workspace.manageAccount.views.check_domain', name='admin_manager.check_domain'),
    url(r'^home$', 'workspace.personalizeHome.views.load', name='admin_manager.load'),
    url(r'^suggest', 'workspace.personalizeHome.views.suggest', name='personalizeHome.suggest'),
    url(r'^upload    ', 'workspace.personalizeHome.views.upload', name='personalizeHome.upload'),
    url(r'^deleteFiles', 'workspace.personalizeHome.views.deleteFiles', name='personalizeHome.deleteFiles'),
    url(r'^create_test_datasets/(?P<quantity>\d+)', 'workspace.manageAccount.views.create_test_datasets', name='admin_manager.create_test_datasets'),
)
