from django.conf.urls import *

urlpatterns = patterns(
    '',
    url(r'^info$', 'workspace.manageAccount.views.action_info', name='admin_manager.action_info'),
    url(r'^info-update$', 'workspace.manageAccount.views.action_info_update', name='admin_manager.action_info_update'),
    url(r'^users$', 'workspace.manageAccount.views.action_users', name='admin_manager.action_users'),
    url(r'^branding$', 'workspace.manageAccount.views.action_branding', name='admin_manager.action_branding'),
    url(r'^branding-update$', 'workspace.manageAccount.views.action_branding_update', name='admin_manager.action_branding_update'),
    url(r'^social$', 'workspace.manageAccount.views.action_social', name='admin_manager.action_social'),
    url(r'^social_update$', 'workspace.manageAccount.views.action_social_update', name='admin_manager.action_social_update'),
    url(r'^domain$', 'workspace.manageAccount.views.action_domain', name='admin_manager.action_domain'),
    url(r'^domain-update$', 'workspace.manageAccount.views.action_domain_update', name='admin_manager.action_domain_update'),
    url(r'^categories$', 'workspace.manageAccount.views.action_categories', name='admin_manager.action_categories'),
    url(r'^create_category$', 'workspace.manageAccount.views.action_create_category', name='admin_manager.action_create_category'),
    url(r'^edit_category$', 'workspace.manageAccount.views.action_edit_category', name='admin_manager.action_edit_category'),
    url(r'^delete_category$', 'workspace.manageAccount.views.action_delete_category', name='admin_manager.action_delete_category'),
    url(r'^create_user$', 'workspace.manageAccount.views.action_create_user', name='admin_manager.action_create_user'),
    url(r'^edit_user$', 'workspace.manageAccount.views.action_edit_user', name='admin_manager.action_edit_user'),
    url(r'^check_email$', 'workspace.manageAccount.views.action_check_email', name='admin_manager.action_check_email'),
    url(r'^check_username', 'workspace.manageAccount.views.action_check_username', name='admin_manager.action_check_username'),
    url(r'^check_domain', 'workspace.manageAccount.views.action_check_domain', name='admin_manager.action_check_domain'),
    url(r'^home$', 'workspace.personalizeHome.views.load', name='admin_manager.action_home'),
    url(r'^suggest', 'workspace.personalizeHome.views.suggest', name='personalizeHome.suggest'),
    url(r'^upload    ', 'workspace.personalizeHome.views.upload', name='personalizeHome.upload'),
    url(r'^deleteFiles', 'workspace.personalizeHome.views.deleteFiles', name='personalizeHome.deleteFiles'),
    url(r'^create_test_datasets/(?P<quantity>\d+)', 'workspace.manageAccount.views.create_test_datasets', name='admin_manager.create_test_datasets'),
)
